### ISSUE TITLE
Add Hologit to catalog

### ISSUE THREAD

**Issue by themightychris** [malleable-systems/malleable.systems#14]
[Hologit](https://github.com/JarvusInnovations/hologit) is a tool I've been working on to enable projects to have CI/CD automations that live in-repo, are extendable, and require zero infrastructure for users to use (while also being able to take advantage of any available infra/peers to accelerate)

**Comment by jryans** [comment]
Seems like an interesting tool! 😄 It definitely seems like it would accelerate and simplify common development hurdles of today.

As for the malleability goals, I feel a bit conflicted. While those of us already in the development world have learned to work with Git, it's not really what I'd consider easy to use, even for those who are experienced developers. Since Hologit builds on top Git, you would need to be familiar with today's development toolchain to make use of it. The malleability effort hopes to make software modification accessible to a much wider audience than today's programmer experts.

At the same time, the attributes you mention above (in-repo, extendable, no infrastructure needed) do align with retaining ownership.

Maybe it would help me if you could explain a bit more about how you view the malleability connection here. 😄

**Comment by jryans** [comment]
For now, I'll close this, but let me know if you're able to clarify how you see it some time!
