### ISSUE TITLE
Consider adding a long form communication medium

### ISSUE THREAD

**Issue by jryans** [malleable-systems/malleable.systems#66]
When we last [talked about it](https://matrix.to/#/!bQveTkYXFyxLJQwcLG:matrix.org/$uFHk4fAR5hLooiyurVzPtBxs51XxY1stEXdtLq9NaEY?via=matrix.org&via=aria-net.org&via=mozilla.org) in 2021-08, there was some desire for a longer form communication medium, such as a web forum like Discourse.

**Comment by karlicoss** [comment]
Yep, Discourse good idea!
Another good option imo might be Zulip, because it's somewhat in between IM and slow forum. It's possible to publish archives as well so they are indexable by search engines, e.g. https://leanprover-community.github.io/archive/

In addition, they'll support public streams soon, so people could view conversations without having to log in https://github.com/zulip/zulip/issues/4817

**Comment by 7h3kk1d** [comment]
I don't have any suggestions for software but it would be great to be able to have less ephemeral more deeply threaded conversations for different topics. If possible though I wonder if we could bridge some notifications into matrix. I'm a little concerned with dividing up the community with it being small.

**Comment by jryans** [comment]
A recent joiner also prefers a slower discussion style medium. They also mentioned https://github.com/nim-lang/nimforum as Discourse alternative.

**Comment by akkartik** [comment]
Another new entrant I'm kicking the wheels on: https://forum.merveilles.town

Repo: https://github.com/cblgh/cerca

**Comment by jryans** [comment]
A [forum](https://forum.malleable.systems/) now exists! Please give it a try. 😄
